# Used Node.js runtime as a base image
FROM node:10

# Set the working directory in the container
WORKDIR /frontend

#copy cur dir to container
COPY . /frontend

# Install Node.js dependencies
RUN npm install 
RUN npm install --save-dev @babel/plugin-proposal-private-property-in-object

# Expose port 3000 for the Node.js application
EXPOSE 3000

# Start the Node.js application
CMD ["npm", "start"]